const result = {
  colors: {
    DEFAULT_COLOR: "#333333",
    PRIMARY_COLOR: "#409EFF",
    PRIMARY_BG_COLOR: "rgb(217, 236, 255)",
    SUCCESS_COLOR: "#67C23A",
    SUCCESS_BG_COLOR: "#D1FFD1",
    WARNING_COLOR: "#E6A23C",
    DANGER_COLOR: "#F56C6C",
    INFO_COLOR: "#909399",
    PRIMARY_TEXT_COLOR: "#303133",
    NORMAL_TEXT_COLOR: "#606266",
    SECONDARY_TEXT_COLOR: "#909399",
    PLACEHOLDER_TEXT_COLOR: "#C0C4CC",
    BLACK_TEXT_COLOR: "#000000",
    WHITE_TEXT_COLOR: "#FFFFFF",
    FIRST_BORDER_COLOR: "#DCDFE6",
    SECOND_BORDER_COLOR: "#E4E7ED",
    THIRD_BORDER_COLOR: "#EBEEF5",
    FOURTH_BORDER_COLOR: "#F2F6FC",
    DEFAULT_TEXT_FONT_SIZE: "14px"
  }
};
export default result;
